import { supabase } from '../lib/supabase';
export const PAGE_SIZE=10;
const postSelect=`id,content,created_at,author_id,campus_id,community_id,profiles:author_id(id,username,full_name,avatar_path),communities:community_id(id,name,avatar_path),post_media(id,media_type,storage_path,sort_order),likes(count),comments(count)`;
async function blockedIds(userId?:string){if(!userId)return [];const r=await supabase.from('blocks').select('blocked_id').eq('blocker_id',userId);return (r.data||[]).map(x=>x.blocked_id)}
export async function fetchFeed(campusId:string,from=0,to=PAGE_SIZE-1,userId?:string){let q=supabase.from('posts').select(postSelect).eq('campus_id',campusId).order('created_at',{ascending:false}).range(from,to);const ids=await blockedIds(userId);if(ids.length)q=q.not('author_id','in',`(${ids.join(',')})`);return q;}
export async function fetchFollowingFeed(userId:string,from=0,to=PAGE_SIZE-1){const f=await supabase.from('follows').select('following_id').eq('follower_id',userId);if(f.error)return {data:null,error:f.error,count:null,status:400,statusText:f.error.message};const blocked=await blockedIds(userId);const ids=(f.data||[]).map(x=>x.following_id).filter(id=>!blocked.includes(id));if(!ids.length)return {data:[],error:null,count:0,status:200,statusText:'OK'} as any;return supabase.from('posts').select(postSelect).in('author_id',ids).order('created_at',{ascending:false}).range(from,to);}
export async function fetchCommunityFeed(communityId:string,from=0,to=PAGE_SIZE-1){return supabase.from('posts').select(postSelect).eq('community_id',communityId).order('created_at',{ascending:false}).range(from,to);}
export async function fetchPost(postId:string){return supabase.from('posts').select(postSelect).eq('id',postId).single();}
export async function createPost(input:{author_id:string;campus_id:string;content:string;community_id?:string|null}){return supabase.from('posts').insert(input).select().single();}
export async function deletePost(postId:string){return supabase.from('posts').delete().eq('id',postId);}
export async function toggleLike(postId:string,profileId:string,liked:boolean){return liked?supabase.from('likes').delete().eq('post_id',postId).eq('profile_id',profileId):supabase.from('likes').insert({post_id:postId,profile_id:profileId});}
export async function listComments(postId:string){return supabase.from('comments').select('id,content,created_at,author_id,profiles:author_id(id,username,full_name,avatar_path)').eq('post_id',postId).order('created_at',{ascending:true});}
export async function addComment(postId:string,authorId:string,content:string){return supabase.from('comments').insert({post_id:postId,author_id:authorId,content}).select().single();}
export async function deleteComment(commentId:string){return supabase.from('comments').delete().eq('id',commentId);}
export async function listCommunities(campusId:string){return supabase.from('communities').select('id,name,slug,description,avatar_path,cover_path,member_count,visibility').eq('campus_id',campusId).order('name');}
export async function getCommunity(id:string){return supabase.from('communities').select('id,name,slug,description,avatar_path,cover_path,member_count,visibility,rules,created_by,campus_id').eq('id',id).single();}
export async function isCommunityMember(id:string,userId:string){return supabase.from('community_members').select('community_id,status,role,created_at').eq('community_id',id).eq('profile_id',userId).maybeSingle();}
export async function joinCommunity(id:string,userId:string,visibility:'public'|'private'='public'){return supabase.from('community_members').insert({community_id:id,profile_id:userId,status:visibility==='private'?'pending':'active'});}
export async function leaveCommunity(id:string,userId:string){return supabase.from('community_members').delete().eq('community_id',id).eq('profile_id',userId);}
export async function listCommunityMembers(id:string){return supabase.from('community_members').select('profile_id,status,role,profiles:profile_id(id,username,full_name,avatar_path)').eq('community_id',id).order('created_at',{ascending:false});}
export async function createCommunity(input:{name:string;slug:string;description:string;campus_id:string;created_by:string;visibility:'public'|'private';rules:string}){return supabase.from('communities').insert(input).select().single();}
export async function listPinnedPosts(id:string){return supabase.from('community_pinned_posts').select('post_id,created_at,posts(id,content,created_at,author_id,campus_id,community_id,profiles:author_id(id,username,full_name,avatar_path),post_media(id,media_type,storage_path,sort_order))').eq('community_id',id).order('created_at',{ascending:false});}
export async function uploadPostMedia(uri:string,userId:string,postId:string,mimeType:string){const response=await fetch(uri);const blob=await response.blob();const extension=mimeType.split('/')[1]||'bin';const path=`${userId}/${postId}/${Date.now()}.${extension}`;const {error}=await supabase.storage.from('post-media').upload(path,blob,{contentType:mimeType,upsert:false});if(error)return {data:null,error};return {data:{path},error:null};}
export async function attachPostMedia(postId:string,media:{media_type:'image'|'video';storage_path:string;sort_order:number}[]){if(!media.length)return {data:[],error:null};return supabase.from('post_media').insert(media.map(x=>({...x,post_id:postId})));}

export async function pinPost(communityId:string,postId:string,userId:string){return supabase.from('community_pinned_posts').insert({community_id:communityId,post_id:postId,pinned_by:userId});}
export async function unpinPost(communityId:string,postId:string){return supabase.from('community_pinned_posts').delete().eq('community_id',communityId).eq('post_id',postId);}
