import { useEffect, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { ArrowLeft, CheckCheck } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { useAuthStore } from '../stores/auth-store';
import { listNotifications, markAllNotificationsRead, markNotificationRead } from '../services/notifications';
import { Avatar } from '../components/Avatar';
import { Skeleton } from '../components/Skeleton';
import { supabase } from '../lib/supabase';
import { EmptyState } from '../components/EmptyState';
import { colors, radius, spacing, type } from '../constants/theme';

export default function Notifications() {
  const insets = useSafeAreaInsets(); const user = useAuthStore(s => s.user); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!user) return; listNotifications(user.id).then(r => { setItems(r.data || []); setLoading(false); }); const ch = supabase.channel(`notifications-${user.id}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'notifications', filter: `recipient_id=eq.${user.id}` }, p => setItems(x => [p.new, ...x])).subscribe(); return () => { supabase.removeChannel(ch); }; }, [user]);
  async function open(n: any) { if (!n.read_at) { await markNotificationRead(n.id); setItems(x => x.map(i => i.id === n.id ? { ...i, read_at: new Date().toISOString() } : i)); } if (n.post_id) router.push({ pathname: '/post/[id]', params: { id: n.post_id } }); else if (n.actor_id) router.push({ pathname: '/profile/[id]', params: { id: n.actor_id } }); }
  return <View style={[styles.page, { paddingTop: insets.top + 8 }]}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.icon}><ArrowLeft size={21} color={colors.text} /></Pressable><Text style={[type.h1, { flex: 1, marginLeft: 12 }]}>Notifications</Text><Pressable onPress={async () => { if (user) await markAllNotificationsRead(user.id); setItems(x => x.map(i => ({ ...i, read_at: new Date().toISOString() }))); }} style={styles.read}><CheckCheck size={16} color={colors.accentStrong} /><Text style={styles.readText}>Read all</Text></Pressable></View>{loading ? <View style={{ padding: spacing.md, gap: 10 }}>{[1, 2, 3].map(x => <Skeleton key={x} height={74} radius={radius.md} />)}</View> : <FlatList data={items} keyExtractor={x => x.id} contentContainerStyle={{ paddingHorizontal: spacing.md, paddingBottom: 24, flexGrow: 1 }} renderItem={({ item }) => <Pressable onPress={() => open(item)} style={[styles.item, !item.read_at && styles.unread]}><Avatar uri={item.profiles?.avatar_path} name={item.profiles?.full_name} /><View style={{ flex: 1, marginLeft: 12 }}><Text style={[styles.message, !item.read_at && { fontWeight: '700' }]}>{item.message || `New ${item.type}`}</Text><Text style={styles.time}>{new Date(item.created_at).toLocaleString()}</Text></View>{!item.read_at ? <View style={styles.dot} /> : null}</Pressable>} ListEmptyComponent={<EmptyState title="You're all caught up" message="New activity will appear here." />} />}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.white }, header: { flexDirection: 'row', alignItems: 'center', padding: spacing.md }, icon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, read: { flexDirection: 'row', alignItems: 'center', gap: 5 }, readText: { ...type.meta, color: colors.accentStrong, fontWeight: '700' }, item: { minHeight: 76, padding: 12, marginBottom: 8, borderRadius: radius.md, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white }, unread: { backgroundColor: colors.accentSoft, borderColor: '#D9ECFF' }, message: { ...type.body, color: colors.text }, time: { ...type.meta, color: colors.subtle, marginTop: 3 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accentStrong, marginLeft: 8 } });
