import { useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { ArrowLeft, LockKeyhole, Pin, UsersRound } from 'lucide-react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useAuthStore } from '../../stores/auth-store';
import { getCommunity, isCommunityMember, joinCommunity, leaveCommunity, fetchCommunityFeed, listCommunityMembers, listPinnedPosts, pinPost, unpinPost } from '../../services/feed';
import { PostCard } from '../../components/PostCard';
import { UserCard } from '../../components/UserCard';
import { EmptyState } from '../../components/EmptyState';
import { Skeleton } from '../../components/Skeleton';
import { colors, radius, spacing, type, shadow } from '../../constants/theme';

export default function CommunityDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const user = useAuthStore(s => s.user);
  const [c, setC] = useState<any>(); const [membership, setMembership] = useState<any>(); const [posts, setPosts] = useState<any[]>([]); const [members, setMembers] = useState<any[]>([]); const [section, setSection] = useState<'feed'|'members'|'rules'>('feed'); const [loading, setLoading] = useState(true); const [pinned, setPinned] = useState<any[]>([]);
  async function load() { if (!id || !user) return; setLoading(true); const [a,b,p,m,pin] = await Promise.all([getCommunity(id), isCommunityMember(id,user.id), fetchCommunityFeed(id,0,19), listCommunityMembers(id), listPinnedPosts(id)]); setC(a.data); setMembership(b.data); setPosts(p.data||[]); setMembers(m.data||[]); setPinned((pin.data||[]).map((x:any)=>x.posts).filter(Boolean)); setLoading(false); }
  useEffect(() => { load(); }, [id,user]);
  async function toggle() { if (!user || !id) return; const active = membership?.status === 'active'; const r = active ? await leaveCommunity(id,user.id) : await joinCommunity(id,user.id,c?.visibility||'public'); if (r.error) Alert.alert('Could not update membership',r.error.message); else load(); }
  if (loading && !c) return <View style={styles.loading}><Skeleton height={220} radius={0} /><View style={styles.skeletonBody}>{[1,2,3].map(x=><Skeleton key={x} height={72} radius={radius.md}/>)}</View></View>;
  const isMember = membership?.status === 'active'; const canModerate = membership?.role === 'admin' || membership?.role === 'moderator';
  const feedData = [...pinned, ...posts.filter(x => !pinned.some(p => p.id === x.id))];
  return <View style={styles.page}><View style={styles.hero}><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={20} color={colors.text} /></Pressable><View style={styles.cover}><View style={styles.communityAvatar}><UsersRound size={27} color={colors.accentStrong} /></View></View><Text style={styles.name}>{c?.name}</Text><View style={styles.meta}><Text style={styles.metaText}>{c?.member_count||0} members</Text><View style={styles.dot} />{c?.visibility === 'private' ? <LockKeyhole size={13} color={colors.muted} /> : null}<Text style={styles.metaText}>{c?.visibility === 'private' ? 'Private' : 'Public'}</Text></View>{c?.description ? <Text style={styles.description}>{c.description}</Text> : null}<Pressable onPress={toggle} style={[styles.join, isMember && styles.joinActive]}><Text style={[styles.joinText, isMember && styles.joinTextActive]}>{membership?.status==='pending'?'Pending approval':isMember?'Leave community':c?.visibility==='private'?'Request to join':'Join community'}</Text></Pressable><View style={styles.tabs}>{[['feed','Posts'],['members','Members'],['rules','About']].map(([v,label])=><Pressable key={v} onPress={()=>setSection(v as any)} style={[styles.tab, section===v && styles.tabActive]}><Text style={[styles.tabText, section===v && styles.tabTextActive]}>{label}</Text></Pressable>)}</View></View>
  {section==='feed' ? <FlatList data={feedData} keyExtractor={x=>x.id} contentContainerStyle={styles.list} renderItem={({item})=><View>{pinned.some(p=>p.id===item.id)?<View style={styles.pinnedLabel}><Pin size={13} color={colors.accentStrong}/><Text style={styles.pinnedText}>Pinned</Text></View>:null}<PostCard post={item} currentUserId={user?.id} liked={false} onLike={async()=>{}}/>{canModerate?<Pressable onPress={async()=>{const isPinned=pinned.some(p=>p.id===item.id);const r=isPinned?await unpinPost(id,item.id):await pinPost(id,item.id,user!.id);if(r.error)Alert.alert('Could not update pin',r.error.message);else load();}} style={styles.moderate}><Text style={styles.moderateText}>{pinned.some(p=>p.id===item.id)?'Unpin post':'Pin post'}</Text></Pressable>:null}</View>} ListHeaderComponent={isMember&&new Date(membership.created_at||0).getTime()>Date.now()-7*24*60*60*1000?<View style={styles.welcome}><Text style={styles.welcomeTitle}>Welcome to {c?.name}</Text><Text style={styles.welcomeText}>Introduce yourself, read the rules and join the conversation.</Text></View>:null} ListEmptyComponent={<EmptyState title="No community posts yet" message="Be the first to share with this community."/>}/> : section==='members' ? <FlatList data={members} keyExtractor={x=>x.profile_id} contentContainerStyle={styles.list} renderItem={({item})=><UserCard user={item.profiles} action={item.role!=='member'?<Text style={styles.role}>{item.role}</Text>:null}/>} ListEmptyComponent={<EmptyState title="No members yet" message="Invite students to join."/>}/> : <View style={styles.rules}><Text style={styles.rulesTitle}>Community rules</Text><Text style={styles.rulesText}>{c?.rules||'Be respectful. Keep the community useful, welcoming and campus-focused.'}</Text></View>}</View>;
}

const styles = StyleSheet.create({ page:{flex:1,backgroundColor:colors.background}, loading:{flex:1,backgroundColor:colors.white}, skeletonBody:{padding:spacing.md,gap:10}, hero:{paddingTop:54,paddingHorizontal:spacing.md,backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.border}, back:{position:'absolute',top:52,left:spacing.md,zIndex:3,width:40,height:40,borderRadius:20,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.border}, cover:{height:92,marginHorizontal:-spacing.md,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'flex-end',paddingBottom:12}, communityAvatar:{width:58,height:58,borderRadius:18,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center',...shadow.card}, name:{...type.h2,color:colors.text,marginTop:14}, meta:{flexDirection:'row',alignItems:'center',gap:6,marginTop:5},metaText:{...type.meta,color:colors.muted},dot:{width:3,height:3,borderRadius:2,backgroundColor:colors.subtle},description:{...type.body,color:colors.muted,marginTop:9,lineHeight:21},join:{height:48,borderRadius:radius.md,backgroundColor:colors.accentStrong,alignItems:'center',justifyContent:'center',marginTop:13},joinActive:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},joinText:{...type.button,color:colors.white},joinTextActive:{color:colors.text},tabs:{height:54,flexDirection:'row',marginTop:12},tab:{flex:1,alignItems:'center',justifyContent:'center',borderBottomWidth:2,borderBottomColor:'transparent'},tabActive:{borderBottomColor:colors.accentStrong},tabText:{...type.label,color:colors.muted},tabTextActive:{color:colors.accentStrong},list:{padding:spacing.md,paddingBottom:30,gap:10,flexGrow:1},welcome:{padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.accentSoft,borderWidth:1,borderColor:'#D9ECFF'},welcomeTitle:{...type.bodyMedium,color:colors.text},welcomeText:{...type.meta,color:colors.muted,marginTop:3},pinnedLabel:{flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:4,paddingBottom:6},pinnedText:{...type.meta,color:colors.accentStrong,fontFamily:'DMSans_700Bold'},moderate:{paddingHorizontal:4,paddingBottom:6},moderateText:{...type.meta,color:colors.accentStrong,fontFamily:'DMSans_700Bold'},role:{...type.meta,color:colors.accentStrong,fontFamily:'DMSans_700Bold'},rules:{padding:spacing.lg},rulesTitle:{...type.h2,color:colors.text},rulesText:{...type.body,color:colors.muted,lineHeight:24,marginTop:12},});
