import { useEffect, useState } from 'react';
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Gamepad2, MoreHorizontal, Send, Circle } from 'lucide-react-native';
import { useAuthStore } from '../../stores/auth-store';
import { listMessages, sendMessage, markConversationRead, createGame } from '../../services/messages';
import { supabase } from '../../lib/supabase';
import { MessageBubble } from '../../components/MessageBubble';
import { EmptyState } from '../../components/EmptyState';
import { colors, radius, spacing, type } from '../../constants/theme';

export default function ChatDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const user = useAuthStore(s => s.user);
  const [items,setItems]=useState<any[]>([]); const [text,setText]=useState(''); const [sending,setSending]=useState(false); const [other,setOther]=useState<any>();
  useEffect(()=>{ if(!id||!user)return; listMessages(id).then(r=>setItems(r.data||[])); markConversationRead(id,user.id); supabase.from('conversation_members').select('profile_id,profiles:profile_id(id,username,full_name,avatar_path)').eq('conversation_id',id).neq('profile_id',user.id).maybeSingle().then(r=>setOther(r.data?.profiles)); const ch=supabase.channel(`messages-${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},p=>{setItems(x=>x.some(m=>m.id===p.new.id)?x:[...x,p.new]); if(p.new.sender_id!==user.id)markConversationRead(id,user.id)}).subscribe(); return()=>{supabase.removeChannel(ch)} },[id,user]);
  async function send(){if(!user||!id||!text.trim()||sending)return;const body=text.trim();setText('');setSending(true);const r=await sendMessage(id,user.id,body);setSending(false);if(r.error){setText(body);Alert.alert('Message failed','Couldn’t send your message. Check your connection and try again.')}}
  async function challenge(){if(!id||!other?.id)return;const r=await createGame(id,other.id);if(r.error)Alert.alert('Game unavailable',r.error.message);else router.push({pathname:'/game/[id]',params:{id:r.data}})}
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.iconButton}><ArrowLeft size={21} color={colors.text}/></Pressable><View style={styles.identity}><View style={styles.avatar}><Text style={styles.avatarText}>{(other?.full_name||other?.username||'?').slice(0,1).toUpperCase()}</Text></View><View><Text style={styles.name}>{other?.full_name||other?.username||'Chat'}</Text><View style={styles.onlineRow}><Circle size={7} color={colors.success} fill={colors.success}/><Text style={styles.online}>Direct message</Text></View></View></View><View style={styles.headerActions}><Pressable onPress={challenge} style={styles.iconButton}><Gamepad2 size={19} color={colors.accentStrong}/></Pressable><Pressable style={styles.iconButton}><MoreHorizontal size={20} color={colors.text}/></Pressable></View></View>
    <FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={styles.list} renderItem={({item})=><MessageBubble item={item} mine={item.sender_id===user?.id}/>} ListEmptyComponent={<EmptyState title="Start a conversation" message="Say hello and share what is happening on campus."/>} showsVerticalScrollIndicator={false}/>
    <View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Message…" placeholderTextColor={colors.subtle} multiline style={styles.input}/><Pressable onPress={send} disabled={sending||!text.trim()} style={({pressed})=>[styles.send,(!text.trim()||sending)&&styles.sendDisabled,pressed&&styles.pressed]}><Send size={18} color={colors.white}/></Pressable></View>
  </KeyboardAvoidingView>
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},header:{paddingHorizontal:spacing.md,paddingTop:54,paddingBottom:12,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:'row',alignItems:'center',backgroundColor:colors.white},iconButton:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'},identity:{flex:1,flexDirection:'row',alignItems:'center',gap:10,marginLeft:4},avatar:{width:40,height:40,borderRadius:20,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},avatarText:{...type.button,color:colors.accentStrong},name:{...type.bodyMedium,color:colors.text},onlineRow:{flexDirection:'row',alignItems:'center',gap:5,marginTop:2},online:{...type.meta,color:colors.muted},headerActions:{flexDirection:'row'},list:{padding:spacing.md,paddingBottom:18,gap:8,flexGrow:1},composer:{borderTopWidth:1,borderTopColor:colors.border,padding:10,backgroundColor:colors.white,flexDirection:'row',alignItems:'flex-end',gap:8},input:{flex:1,minHeight:46,maxHeight:110,borderRadius:23,backgroundColor:colors.surface,paddingHorizontal:16,paddingVertical:12,color:colors.text,fontFamily:'DMSans_400Regular',fontSize:15},send:{width:46,height:46,borderRadius:23,backgroundColor:colors.accentStrong,alignItems:'center',justifyContent:'center'},sendDisabled:{opacity:.4},pressed:{transform:[{scale:.95}]}});
