import { useEffect, useState } from 'react';
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ArrowLeft, Send } from 'lucide-react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useAuthStore } from '../../stores/auth-store';
import { fetchPost, listComments, addComment, deleteComment } from '../../services/feed';
import { PostCard } from '../../components/PostCard';
import { Avatar } from '../../components/Avatar';
import { Skeleton } from '../../components/Skeleton';
import { EmptyState } from '../../components/EmptyState';
import { colors, radius, spacing, type } from '../../constants/theme';

export default function PostDetail() {
  const { id } = useLocalSearchParams<{id:string}>(); const user = useAuthStore(s=>s.user); const [p,setP]=useState<any>(); const [comments,setComments]=useState<any[]>([]); const [text,setText]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){if(!id)return;const[a,b]=await Promise.all([fetchPost(id),listComments(id)]);setP(a.data);setComments(b.data||[])} useEffect(()=>{load()},[id]);
  async function comment(){if(!user||!id||!text.trim())return;setBusy(true);const r=await addComment(id,user.id,text.trim());setBusy(false);if(r.error)Alert.alert('Could not comment','Your comment was not posted. Try again.');else{setText('');load()}}
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={8}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><ArrowLeft size={20} color={colors.text}/></Pressable><Text style={styles.title}>Post</Text></View>{!p?<View style={styles.loading}><Skeleton height={380} radius={radius.lg}/><Skeleton height={72} radius={radius.md}/><Skeleton height={72} radius={radius.md}/></View>:<FlatList data={comments} keyExtractor={x=>x.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.list} ListHeaderComponent={<View><PostCard post={p} currentUserId={user?.id} liked={false} onLike={async()=>{}}/><View style={styles.commentsHeader}><Text style={styles.commentsTitle}>Comments</Text><Text style={styles.commentsCount}>{comments.length}</Text></View></View>} renderItem={({item})=><View style={styles.comment}><Avatar uri={item.profiles?.avatar_path} name={item.profiles?.full_name} size={40}/><View style={styles.commentBody}><View style={styles.commentTop}><Text style={styles.commentName}>{item.profiles?.full_name||item.profiles?.username}</Text><Text style={styles.commentTime}>{new Date(item.created_at).toLocaleDateString()}</Text></View><Text style={styles.commentText}>{item.content}</Text></View>{item.author_id===user?.id?<Pressable onPress={async()=>{const r=await deleteComment(item.id);if(r.error)Alert.alert('Could not delete',r.error.message);else load()}}><Text style={styles.delete}>×</Text></Pressable>:null}</View>} ListEmptyComponent={<EmptyState title="No comments yet" message="Start the conversation."/>}/>}<View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Add a comment…" placeholderTextColor={colors.subtle} style={styles.input} multiline/><Pressable onPress={comment} disabled={busy||!text.trim()} style={[styles.send,{opacity:busy||!text.trim()?0.45:1}]}><Send size={18} color={colors.white}/></Pressable></View></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},header:{height:58,paddingHorizontal:spacing.md,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:colors.border},back:{width:40,height:40,borderRadius:20,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},title:{...type.h3,color:colors.text,marginLeft:12},loading:{padding:spacing.md,gap:10},list:{padding:spacing.md,paddingBottom:90,gap:10},commentsHeader:{flexDirection:'row',alignItems:'center',paddingVertical:spacing.lg},commentsTitle:{...type.h3,color:colors.text},commentsCount:{...type.meta,color:colors.muted,marginLeft:6},comment:{padding:12,borderRadius:radius.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'flex-start'},commentBody:{flex:1,marginLeft:10},commentTop:{flexDirection:'row',alignItems:'center'},commentName:{...type.bodyMedium,color:colors.text,flex:1},commentTime:{...type.meta,color:colors.subtle},commentText:{...type.body,color:colors.text,marginTop:3},delete:{fontSize:20,color:colors.subtle,paddingHorizontal:5},composer:{position:'absolute',left:0,right:0,bottom:0,minHeight:66,padding:10,paddingHorizontal:spacing.md,backgroundColor:colors.white,borderTopWidth:1,borderTopColor:colors.border,flexDirection:'row',alignItems:'flex-end',gap:8},input:{flex:1,minHeight:44,maxHeight:100,borderRadius:22,backgroundColor:colors.surface,paddingHorizontal:16,paddingVertical:10,fontFamily:'DMSans_400Regular',fontSize:15,color:colors.text},send:{width:44,height:44,borderRadius:22,backgroundColor:colors.accentStrong,alignItems:'center',justifyContent:'center'}});
